### ISSUE TITLE
disbale autocomplete for billing Street Address

### ISSUE THREAD

**Issue by bloggerpact** [ScottParsons/magento-address-autocomplete#1]
Is there any way to stop auto-filling street address? Please help me to disable auto-filling for street address

![image](https://user-images.githubusercontent.com/22036537/29110396-205de87a-7d04-11e7-97aa-26551ff8c51f.png)

**Comment by Turiknox** [comment]
Hello.

Would you be able to give me an example of what you're trying to do? If you need to change the billing field that the dropdown appears underneath (i.e. the autocomplete), you can do so within System -> Configuration -> Turiknox -> Address Autocomplete, and change the 'Billing Address Field To Use For Autocomplete' option.
