### ISSUE TITLE
Add Streetname And Housenumber to Addressfield 1

### ISSUE THREAD

**Issue by sasoriza** [ScottParsons/magento-address-autocomplete#2]
Is it possible to populate address field 1 with both values instead of adding housenumber to address field 1 and street name to address field 2?

**Comment by sasoriza** [comment]
This was pretty straight forward:

        if (address['street_number'] && address['route']) {
            address['route'] = address['route'] + " " + address['street_number'];
            delete address['street_number'];
        }

Thanks for this nice extension!

**Comment by Turiknox** [comment]
Hello,

Sorry I wasn't able to get back to you sooner! I'm glad you have found a solution and like the extension.

**Comment by dsanderss** [comment]
Can you please help me?
Where do i place this code?
