### ISSUE TITLE
Admin Magento System Configuration

### ISSUE THREAD

**Issue by Oscar-Wagento** [ScottParsons/magento-address-autocomplete#3]
Hi, right now i have this problem after clicking Turiknox-> address autocomplete after clicking:

![magento admin](https://user-images.githubusercontent.com/36160350/41441207-a9cad5fc-6fff-11e8-8793-5d1e37ecf0cb.png)

Please I installed with Modman and i cleaned cache
Magento Version: 1.9

Thanks

**Comment by Oscar-Wagento** [comment]
Please @ScottParsons  i need to add the api key but i can't due to 404 :(

**Comment by ScottParsons** [comment]
Hi @Oscar-Wagento, did you try re-logging into the admin area for the ACL permissions to update?

**Comment by Oscar-Wagento** [comment]
Thanks for answering @ScottParsons  yes i did and now in the admin is working, but now i got this issue: 

`Google Maps JavaScript API error: ApiNotActivatedMapError https://developers.google.com/maps/documentation/javascript/error-messages#api-not-activated-map-error`

Please help!

**Comment by Oscar-Wagento** [comment]
it only happens in the form for billing... what am i doing wrong?

**Comment by ScottParsons** [comment]
@Oscar-Wagento I believe you need to enable the Maps API from the Google Cloud Console.

Take a look at [this link](https://support.google.com/googleapi/answer/6158841) which hopefully will help you fix the issue.

**Comment by Oscar-Wagento** [comment]
ooh let me check...

**Comment by Oscar-Wagento** [comment]
@ScottParsons  i still get the error and i followed the steps. Can i have some assitance from you ???

**Comment by Oscar-Wagento** [comment]
This is whats its happening @ScottParsons 

![foto](https://user-images.githubusercontent.com/36160350/41625129-b8bfbbf6-73e5-11e8-84eb-276f5f4233b2.png)

**Comment by Oscar-Wagento** [comment]
Hi @ScottParsons  right now it is working... i thought at the beginning it was the API key but the wrong thing that i did is that i was using an API for places and not for the map. Right now is working in Magento 1 :D
