### ISSUE TITLE
Avoid autofill Telephone

### ISSUE THREAD

**Issue by Oscar-Wagento** [ScottParsons/magento-address-autocomplete#4]
HI @ScottParsons  

Is there any way how to avoid the autofill in the field Telephone? i guess it is on addressautocomplete.js ... but i dont know how... any suggestions?

Thanks!

**Comment by sprankhub** [comment]
The telephone field is not autofilled by this extension. Only these fields are filled:

- street1
- street2
- city
- region
- country_id / country
- postcode

See here: https://github.com/ScottParsons/magento-address-autocomplete/blob/69c8d3f89223694545d57fa2fc6b6a57c0481dd5/js/turiknox/addressautocomplete.js#L20-L53
